name: Keep Node API Alive

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes (UTC)

jobs:
  ping-node:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Node API health route
        run: curl -s -o /dev/null -w "%{http_code}" https://upskillme-e2tz.onrender.com/health || echo "API Unreachable"
